/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
/* Header for class com_example_jnitest_Jclass */

#ifndef _TEST_H_
#define _TEST_H_
#ifdef __cplusplus //标识支持c++语法
extern "C" {
#endif
/*
 * Class:     com_example_jnitest_Jclass
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnitest_Jclass_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jnitest_Jclass
 * Method:    getIntFromC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_jnitest_Jclass_getIntFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnitest_Jclass
 * Method:    passArrayMethod
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_Jclass_passArrayMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_jnitest_Jclass
 * Method:    createArrayMethod
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_jnitest_Jclass_createArrayMethod
  (JNIEnv *, jobject, jint);


/*
 * Class:     com_example_jnitest_Jclass
 * Method:    accessFile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnitest_Jclass_accessFile
  (JNIEnv *, jclass);


/*
 * Class:     com_example_jnitest_Jclass
 * Method:    accessFile2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnitest_Jclass_accessFile2
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnitest_Jclass
 * Method:    setCount
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_Jclass_setCount
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnitest_Jclass
 * Method:    accessMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_Jclass_accessMethod
  (JNIEnv *, jobject);


/*
 * Class:     com_example_jnitest_Jclass
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_Jclass_accessStaticMethod
  (JNIEnv *, jobject);


/*
 * Class:     com_example_jnitest_Jclass
 * Method:    sort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_Jclass_sort
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_jnitest_Jclass
 * Method:    deleteLocalValue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_Jclass_deleteLocalValue
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnitest_Jclass
 * Method:    createGloablValue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_Jclass_createGloablValue
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnitest_Jclass
 * Method:    getGloablValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnitest_Jclass_getGloablValue
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnitest_Jclass
 * Method:    deleteGloablValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnitest_Jclass_deleteGloablValue
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnitest_Jclass
 * Method:    exception
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_Jclass_exception
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnitest_Jclass
 * Method:    fileMerge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_Jclass_fileMerge
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnitest_Jclass
 * Method:    fileSplit
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_jnitest_Jclass_fileSplit
  (JNIEnv *, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif //_TEST_H_
